### ISSUE TITLE
Specify license version & include license

### ISSUE THREAD

**Issue by pmlandwehr** [mbr/shutilwhich#2]
Hey-lo,

I've started building a version of shutilwhich using [`conda`](https://conda.pydata.org) as part of the [conda-forge](conda-forge.github.io) community channel. (see [here.](https://github.com/conda-forge/staged-recipes/pull/1605)) We like to include hard-links to the license in the package, but that requires both a LICENSE file and a MANIFEST.in file specifying that LICENSE should be included. Would you consider adding one?  Also, can you specify _what version_ of the PSF license you're using for `shutilwhich`?

**Comment by mbr** [comment]
It's late and dealing with licenses is never pleasant, but I think the latest commit should clear things up. Could you check if that is satisfactory?

**Comment by pmlandwehr** [comment]
These look great - we'll incorporate them as soon as you put the next version on pypi. Thanks!

**Comment by pmlandwehr** [comment]
Oops, no - one issue: the include files in `MANIFEST.in` should have an `include` before them: `include LICENSE`, etc.
